theme: osuny
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  persons:
    single:
      backlinks: true
  organizations:
    single:
      backlinks: true